### ISSUE TITLE
同步无效

### ISSUE THREAD

**Issue by kelvv** [cnpm/cnpmjs.org#944]

**Comment by kelvv** [comment]
已经安装成功

mysql ＋ cnpm

也可以外部访问，但是在手动去同步express的时候，log是说成功的，但是实际上没有同步成功

**Comment by dead-horse** [comment]
查一下数据库和文件系统

**Comment by kelvv** [comment]
数据库安装成功的，也有数据写入，

[2016-06-02 13:04:20] user: anonymous, sync argps worker start, 1 concurrency, nodeps: false, publish: false
[2016-06-02 13:04:28] ----------------- Syncing upstream https://registry.npm.taobao.org/argps/sync/log/574103 -------------------
[2016-06-02 13:04:28] [2016-06-02 12:04:28] user: anonymous, sync argps worker start, 1 concurrency, nodeps: false, publish: false
[2016-06-02 12:04:28] ----------------- Syncing upstream https://r.cnpmjs.org/argps/sync/log/139260 -------------------
[2016-06-02 13:04:31] [2016-06-02 12:04:28] [2016-06-02 12:04:28] user: anonymous, sync argps worker start, 1 concurrency, nodeps: false, publish: false
[2016-06-02 12:04:28] ----------------- Syncing argps -------------------
[2016-06-02 12:04:28] [c#0] [argps] pkg status: 200, start...
[2016-06-02 12:04:28]   [argps] found 0 missing star users
[2016-06-02 12:04:28]   [argps] all versions are exists
[2016-06-02 12:04:28]   [argps] no versions need to deleted
[2016-06-02 12:04:28]   [argps] all 1 npm users exists
[2016-06-02 12:04:28] [c#0] [argps] synced success, 0 versions: 
[2016-06-02 12:04:28] ----------------- Synced argps success -------------------
[2016-06-02 12:04:28] [Upstream done] Sync argps package finished, 1 success, 0 fail
Success: [ argps ]
Fail: [  ]
[2016-06-02 12:04:28] ----------------- Synced upstream https://r.cnpmjs.org/argps/sync/log/139260 -------------------
[2016-06-02 12:04:28] ----------------- Syncing argps -------------------
[2016-06-02 12:04:28] [c#0] [argps] pkg status: 200, start...
[2016-06-02 12:04:28]   [argps] found 0 missing star users
[2016-06-02 12:04:28]   [argps] all versions are exists
[2016-06-02 12:04:28]   [argps] no versions need to deleted
[2016-06-02 12:04:28]   [argps] all 1 npm users exists
[2016-06-02 12:04:28] [c#0] [argps] synced success, 0 versions: 
[2016-06-02 12:04:28] ----------------- Synced argps success -------------------
[2016-06-02 12:04:28] [Upstream done] Sync argps package finished, 1 success, 0 fail
Success: [ argps ]
Fail: [  ]
[2016-06-02 13:04:31] ----------------- Synced upstream https://registry.npm.taobao.org/argps/sync/log/574103 -------------------
[2016-06-02 13:04:31] [c#0] [undefined] syncModel is none, ignore
[2016-06-02 13:04:31] [done] Sync argps package finished, 0 success, 0 fail
Success: [  ]
Fail: [  ]

**Comment by dead-horse** [comment]
> [2016-06-02 13:04:31] [c#0] [undefined] syncModel is none, ignore
> [2016-06-02 13:04:31] [done] Sync argps package finished, 0 success, 0 fail

你配置成了不同步。所以你这边是不会同步到自己的源的，配置里面改一下

**Comment by xiaqun** [comment]
How to modify the configuration file（index.js）

**Comment by alsotang** [comment]
use Vim or Sublime or Atom, whatever editor you like

**Comment by xiaqun** [comment]
'use strict';

var mkdirp = require('mkdirp');
var copy = require('copy-to');
var path = require('path');
var fs = require('fs');
var os = require('os');

var version = require('../package.json').version;

var root = path.dirname(__dirname);
var dataDir = path.join(process.env.HOME || root, '.cnpmjs.org');

var config = {
  version: version,
  dataDir: dataDir,

  /**
   * Cluster mode
   */
  enableCluster: false,
  numCPUs: os.cpus().length,

  /*
   * server configure
   */

  registryPort: 7001,
  webPort: 7002,
  //bindingHost: '127.0.0.1', // only binding on 127.0.0.1 for local access

  // debug mode
  // if in debug mode, some middleware like limit wont load
  // logger module will print to stdout
  debug: process.env.NODE_ENV === 'development',
  // page mode, enable on development env
  pagemock: process.env.NODE_ENV === 'development',
  // session secret
  sessionSecret: 'cnpmjs.org test session secret',
  // max request json body size
  jsonLimit: '10mb',
  // log dir name
  logdir: path.join(dataDir, 'logs'),
  // update file template dir
  uploadDir: path.join(dataDir, 'downloads'),
  // web page viewCache
  viewCache: false,

  // config for koa-limit middleware
  // for limit download rates
  limit: {
    enable: false,
    token: 'koa-limit:download',
    limit: 1000,
    interval: 1000 * 60 * 60 * 24,
    whiteList: [],
    blackList: [],
    message: 'request frequency limited, any question, please contact fengmk2@gmail.com',
  },

  enableCompress: false, // enable gzip response or not

  // default system admins
  admins: {
    // name: email
    fengmk2: 'fengmk2@gmail.com',
    admin: 'admin@cnpmjs.org',
    dead_horse: 'dead_horse@qq.com',
  },

  // email notification for errors
  // check https://github.com/andris9/Nodemailer for more informations
  mail: {
    enable: false,
    appname: 'cnpmjs.org',
    from: 'cnpmjs.org mail sender <adderss@gmail.com>',
    service: 'gmail',
    auth: {
      user: 'address@gmail.com',
      pass: 'your password'
    }
  },

  logoURL: 'https://os.alipayobjects.com/rmsportal/oygxuIUkkrRccUz.jpg', // cnpm logo image url
  adBanner: '',
  customReadmeFile: '', // you can use your custom readme file instead the cnpm one
  customFooter: '', // you can add copyright and site total script html here
  npmClientName: 'cnpm', // use `${name} install package`
  packagePageContributorSearch: true, // package page contributor link to search, default is true

  // max handle number of package.json `dependencies` property
  maxDependencies: 200,
  // backup filepath prefix
  backupFilePrefix: '/cnpm/backup/',

  /**
   * database config
   */

  database: {
    db: 'cnpmjs_test',
    username: 'root',
    password: '123456',

    // the sql dialect of the database
    // - currently supported: 'mysql', 'sqlite', 'postgres', 'mariadb'
    dialect: 'mysql',

    // custom host; default: 127.0.0.1
    host: '127.0.0.1',

    // custom port; default: 3306
    port: 3306,

    // use pooling in order to reduce db connection overload and to increase speed
    // currently only for mysql and postgresql (since v1.5.0)
    pool: {
      maxConnections: 10,
      minConnections: 0,
      maxIdleTime: 30000
    },

    // the storage engine for 'sqlite'
    // default store into ~/.cnpmjs.org/data.sqlite
    storage: path.join(dataDir, 'data.sqlite'),

    logging: !!process.env.SQL_DEBUG,
  },

  // package tarball store in local filesystem by default
  nfs: require('fs-cnpm')({
    dir: path.join(dataDir, 'nfs')
  }),
  // if set true, will 302 redirect to `nfs.url(dist.key)`
  downloadRedirectToNFS: false,

  // registry url name
  registryHost: 'r.cnpmjs.org',

  /**
   * registry mode config
   */

  // enable private mode or not
  // private mode: only admins can publish, other users just can sync package from source npm
  // public mode: all users can publish
  enablePrivate: true,
//  scopes: ['@cnpm or @cnpmtest'],
//  syncModel: 'exist',

  // registry scopes, if don't set, means do not support scopes
  scopes: [ '@cnpm', '@cnpmtest', '@cnpm-test' ],

  // some registry already have some private packages in global scope
  // but we want to treat them as scoped private packages,
  // so you can use this white list.
  privatePackages: [],

  /**
   * sync configs
   */

  // the official npm registry
  // cnpm wont directly sync from this one
  // but sometimes will request it for some package infomations
  // please don't change it if not necessary
  officialNpmRegistry: 'https://registry.npmjs.com',

  // sync source, upstream registry
  // If you want to directly sync from official npm's registry
  // please drop them an email first
  sourceNpmRegistry: 'https://registry.npm.taobao.org',

  // upstream registry is base on cnpm/cnpmjs.org or not
  // if your upstream is official npm registry, please turn it off
  sourceNpmRegistryIsCNpm: true,

  // if install return 404, try to sync from source registry
  syncByInstall: true,

  // sync mode select
  // none: do not sync any module, proxy all public modules from sourceNpmRegistry
  // exist: only sync exist modules
  // all: sync all modules
  syncModel: 'none', // 'none', 'all', 'exist'

  syncConcurrency: 1,
  // sync interval, default is 10 minutes
  syncInterval: '10m',

  // sync polular modules, default to false
  // because cnpm can't auto sync tag change for now
  // so we want to sync popular modules to ensure their tags
  syncPopular: false,
  syncPopularInterval: '1h',
  // top 100
  topPopular: 100,

  // sync devDependencies or not, default is false
  syncDevDependencies: false,

  // changes streaming sync
  syncChangesStream: false,
  handleSyncRegistry: 'http://127.0.0.1:7001',

  // badge subject on http://shields.io/
  badgePrefixURL: 'https://img.shields.io/badge',
  badgeSubject: 'cnpm',

  // custom user service, @see https://github.com/cnpm/cnpmjs.org/wiki/Use-Your-Own-User-Authorization
  // when you not intend to ingegrate with your company's user system, then use null, it would
  // use the default cnpm user system
  userService: null,

  // always-auth https://docs.npmjs.com/misc/config#always-auth
  // Force npm to always require authentication when accessing the registry, even for GET requests.
  alwaysAuth: false,

  // if you're behind firewall, need to request through http proxy, please set this
  // e.g.: `httpProxy: 'http://proxy.mycompany.com:8080'`
  httpProxy: null,
};

if (process.env.NODE_ENV !== 'test') {
  var customConfig;
  if (process.env.NODE_ENV === 'development') {
    customConfig = path.join(root, 'config', 'config.js');
  } else {
    // 1. try to load `$dataDir/config.json` first, not exists then goto 2.
    // 2. load config/config.js, everything in config.js will cover the same key in index.js
    customConfig = path.join(dataDir, 'config.json');
    if (!fs.existsSync(customConfig)) {
      customConfig = path.join(root, 'config', 'config.js');
    }
  }
  if (fs.existsSync(customConfig)) {
    copy(require(customConfig)).override(config);
  }
}

mkdirp.sync(config.logdir);
mkdirp.sync(config.uploadDir);

module.exports = config;

config.loadConfig = function (customConfig) {
  if (!customConfig) {
    return;
  }
  copy(customConfig).override(config);
};

**Comment by xiaqun** [comment]
我用的mysql，但是配置里面的是sqlite
// the storage engine for 'sqlite'
// default store into ~/.cnpmjs.org/data.sqlite
storage: path.join(dataDir, 'data.sqlite'),
数据库里面没有写入

**Comment by xuanjinliang** [comment]
syncModel: 'exist'// 'none', 'all', 'exist'
